export const SSE_EVENTS = {
  ADVISOR_USER_BALANCE_UPDATE: 'ADVISOR_USER_BALANCE_UPDATE',
  ADVISOR_MATCH_SCORE_UPDATE: 'ADVISOR_MATCH_SCORE_UPDATE',
  ADVISOR_MATCH_STATUS_CHANGE: 'ADVISOR_MATCH_STATUS_CHANGE',
  ADVISOR_PREDICTION_SETTLED: 'ADVISOR_PREDICTION_SETTLED',
} as const;
